model_name: 'nikas_model'
default_params: 
  vector_size: 1024
  window: 5
  alpha: 0.025
  min_alpha: 0.001
  max_vocab_size: 10000

hyperparameter_tuning:
  enabled: true
  params:
    vector_size: [512,1024]
    window: [5]
    alpha: [0.025]
    min_alpha: [0.001]
    max_vocab_size: [10000, 100000]
